import { logger } from '../utils/logger';
import { Router, Response } from 'express';
import { prisma } from '../lib/prisma';
import { authenticateToken, AuthenticatedRequest, requireRole } from '../middleware/auth';
import { Roles, Permissions } from '../shared';
import permissionsRouter from './admin/permissions';
import attendanceRouter from './admin/attendance';

const router = Router();
const p = prisma;

// Mount dynamic permissions management router
router.use('/', permissionsRouter);

// Mount attendance correction router
router.use('/', attendanceRouter);

/**
 * Technical Admin restricted routes for deep telemetry, auditing, and emergency controls.
 * Adheres strictly to SDD Golden Rule #2 (Admin Invincibility & Isolation).
 */

// GET /api/v1/admin/system-metrics
// Returns holistic DB record counts and potential leakage indicators
router.get(
  '/system-metrics',
  authenticateToken,
  requireRole([Roles.ADMIN]),
  async (req: AuthenticatedRequest, res: Response) => {
    try {
      const [
        totalLeads,
        totalProperties,
        totalEmployees,
        totalAuditEvents,
        recentErrors
      ] = await Promise.all([
        p.lead.count(),
        p.property.count(),
        p.employee.count(),
        p.auditEvent.count(),
        p.auditEvent.count({ where: { action: 'SYSTEM_ERROR' } }) // Assuming we track these
      ]);

      return res.status(200).json({
        totalLeads,
        totalProperties,
        totalEmployees,
        totalAuditEvents,
        recentErrors,
        databaseStatus: 'HEALTHY',
        activeConnections: 1 // Simulated for now
      });
    } catch (error) {
      logger.error('[Admin] System metrics fetch failed:', error);
      return res.status(500).json({ error: 'Failed to retrieve system telemetry' });
    }
  }
);


// GET /api/v1/admin/audit-logs
// Returns the raw audit trail for forensic analysis (Data Leakage tracking)
router.get(
  '/audit-logs',
  authenticateToken,
  requireRole([Roles.ADMIN]),
  async (req: AuthenticatedRequest, res: Response) => {
    try {
      const events = await p.auditEvent.findMany({
        orderBy: { created_at: 'desc' },
        take: 150, // Limit for performance
      });

      // Hydrate actor details in-memory since Prisma schema lacks strict relation
      const actorIds = [...new Set(events.map((e: any) => e.actor_id))];
      const actors = await p.employee.findMany({
        where: { id: { in: actorIds as number[] } },
        select: { id: true, employee_code: true, roles: { select: { role: { select: { name: true } } } } }
      });

      const actorMap = new Map<number, { code: string; role: string }>(
        actors.map((a: any) => [
          a.id,
          { code: a.employee_code, role: a.roles?.[0]?.role?.name || 'Unknown' }
        ])
      );

      const hydratedEvents = events.map((event: any) => ({
        ...event,
        actor_code: actorMap.get(event.actor_id)?.code || `ID:${event.actor_id}`,
        actor_role: actorMap.get(event.actor_id)?.role || 'N/A'
      }));

      return res.status(200).json({ logs: hydratedEvents });
    } catch (error) {
      logger.error('[Admin] Audit logs fetch failed:', error);
      return res.status(500).json({ error: 'Failed to retrieve forensic audit trail' });
    }
  }
);

// GET /api/v1/admin/security-alerts
// Returns Security Alerts and Anomalies
router.get(
  '/security-alerts',
  authenticateToken,
  requireRole([Roles.ADMIN, Roles.MD]),
  async (req: AuthenticatedRequest, res: Response) => {
    try {
      const isAdmin = req.user!.roles.includes(Roles.ADMIN as any);
      let actorIdsFilter = undefined;

      if (!isAdmin) {
        // MD can only see alerts generated by their own company's employees
        const companyEmployees = await p.employee.findMany({
          where: { company_id: req.user!.companyId },
          select: { id: true }
        });
        actorIdsFilter = { in: companyEmployees.map((e: any) => e.id) };
      }

      const alerts = await p.auditEvent.findMany({
        where: { 
          action: 'SECURITY_ALERT',
          ...(actorIdsFilter ? { actor_id: actorIdsFilter } : {})
        },
        orderBy: { created_at: 'desc' },
        take: 50,
      });
      return res.status(200).json({ alerts });
    } catch (error) {
      logger.error('[Admin] Security alerts fetch failed:', error);
      return res.status(500).json({ error: 'Failed to retrieve security alerts' });
    }
  }
);
// Emergency kill-switch trigger
router.post(
  '/emergency/lockdown',
  authenticateToken,
  requireRole([Roles.ADMIN]),
  async (req: AuthenticatedRequest, res: Response) => {
    try {
      const actorId = req.user?.employeeId || (req.user as any)?.userId || 1;

      // Log the extreme action
      await p.auditEvent.create({
        data: {
          actor_id: actorId,
          action: 'TRIGGER_EMERGENCY_LOCKDOWN',
          entity_type: 'SYSTEM',
          entity_id: 0,
          old_value: 'NORMAL',
          new_value: 'LOCKED',
        }
      });

      // Future Implementation: Broadcast socket event to invalidate all active JWTs 
      // and redirect all connected clients to a maintenance screen.
      
      return res.status(200).json({ 
        message: 'System Lockdown Triggered Successfully. All operations halted.',
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      logger.error('[Admin] Emergency lockdown failed:', error);
      return res.status(500).json({ error: 'Failed to execute system lockdown command' });
    }
  }
);

import { clearCache } from '../utils/cache';

// POST /cache/clear
// Admin endpoint to manually flush the in-memory cache
router.post(
  '/cache/clear',
  authenticateToken,
  requireRole([Roles.ADMIN]),
  (req: AuthenticatedRequest, res: Response) => {
    try {
      const stats = clearCache();
      return res.status(200).json({ 
        message: 'Cache cleared successfully',
        keysFlushed: stats.keys
      });
    } catch (error) {
      logger.error('[Admin] Cache clear failed:', error);
      return res.status(500).json({ error: 'Failed to clear cache' });
    }
  }
);

export default router;
